#!/usr/bin/env perl
use strict;
use warnings;

# Print out every single chromatic note and the modes of each.

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Util);
use MIDI::Util qw(midi_format);
use Music::Scales qw(get_scale_notes);

for my $note (get_scale_notes('C', 'chromatic')) {
    for my $mode (qw(ionian dorian phrygian lydian mixolydian aeolian locrian)) {
        my @scale = midi_format(get_scale_notes($note, $mode));
        ($note) = midi_format($note);
        printf "scale(%s, %s, [%s]).\n", $note, $mode, join(', ', @scale);
    }
}
