#!/usr/bin/env perl
use strict;
use warnings;

##
# Musical dice game, attributed to Mozart
##

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Util);
use MIDI::Util qw(setup_score set_chan_patch);

my $max    = shift || 16; # Number of measures to produce
my $bpm    = shift || 90; # Beats per minute
my $tpatch = shift || 4;  # Treble
my $bpatch = shift || 35; # Bass

# Declare the available measures
my $total_measures = 8;
my @measures  = map { my $sub = 'measure' . $_;       \&$sub } 1 .. $total_measures;
my @measuresb = map { my $sub = 'measure' . $_ . 'b'; \&$sub } 1 .. $total_measures;

# Setup the MIDI score
my $score = setup_score(bpm => $bpm);

# Choose the measures to play
my @choices;
for (0 .. $max - 1) {
    push @choices, int rand @measures;
}

# Define the procedures to actually play the chosen measures
my $tproc = sub {
    set_chan_patch($score, 0, $tpatch);
    $measures[$_]->() for @choices;
};
my $bproc = sub {
    set_chan_patch($score, 1, $bpatch);
    $measuresb[$_]->()for @choices;
};

# Mash the phrases together as MIDI tracks
$score->synch($tproc, $bproc);

# Write the score to a MIDI file
$score->write_score("$0.mid");

# Available measures:

sub measure1 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en F5));
    $score->n(qw(en D5));
    $score->n(qw(en G5));
}
sub measure1b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en F3));
    $score->n(qw(en D3));
    $score->n(qw(en G3));
}
sub measure2 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en A4));
    $score->n(qw(sn Fs4));
    $score->n(qw(sn G4));
    $score->n(qw(sn B4));
    $score->n(qw(sn G5));
}
sub measure2b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn B2 G3));
    $score->r(qw(en));
}
sub measure3 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en G5));
    $score->n(qw(en C5));
    $score->n(qw(en E5));
}
sub measure3b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn C3 E3));
    $score->r(qw(en));
}
sub measure4 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en G5));
    $score->n(qw(qn D5));
}
sub measure4b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(sn G2));
    $score->n(qw(sn B2));
    $score->n(qw(en G3));
    $score->n(qw(en B2));
}
sub measure5 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn G5 D5 B4 G4));
    $score->r(qw(en));
}
sub measure5b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en G2));
    $score->n(qw(sn B3 G3));
    $score->n(qw(sn G3 F3));
    $score->n(qw(sn Fs3 E3));
    $score->n(qw(sn E3 D3));
}
sub measure6 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en G4));
    $score->n(qw(en C5));
    $score->n(qw(en E5));
}
sub measure6b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn C3 E3));
    $score->r(qw(en));
}
sub measure7 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(sn E5));
    $score->n(qw(sn C5));
    $score->n(qw(sn E5));
    $score->n(qw(sn G5));
    $score->n(qw(sn C6));
    $score->n(qw(sn G5));
}
sub measure7b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn C3 G3));
    $score->r(qw(en));
}
sub measure8 {
    print '', (caller(0))[3], "\n";
    $score->n(qw(qn C5));
    $score->r(qw(en));
}
sub measure8b {
    print '', (caller(0))[3], "\n";
    $score->n(qw(en C3));
    $score->n(qw(en G2));
    $score->n(qw(en C2));
}
