#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact qw(ddc);

use Music::Guidonian;
use Music::Scales qw(get_scale_nums);

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Util);
use MIDI::Util qw(setup_score);

my $text  = shift || 'Lorem ipsum dolor sit';
my $scale = shift || 'major';
my $bpm   = shift || 200;
my $patch = shift || 4;
my $vol   = shift || 120;
my $min   = shift || 48;
my $max   = shift || 72;

# Get the scale intervals
my @scale     = (get_scale_nums($scale), 12);
my @intervals = map { $scale[$_ + 1] - $scale[$_]} 0 .. $#scale - 1;

my $mg = Music::Guidonian->new(
  key_set => {
    intervals => \@intervals,
    keys => [qw(a e i o u)],
    min => $min,
    max => $max,
  }
);

my @vowels = lc($text) =~ m/([aeiou])/g;

my $iter = $mg->iterator(\@vowels);
 
my $phrase = $iter->();

my $score = setup_score(bpm => $bpm, patch => $patch, volume => $vol);

$score->n('wn', $_) for @$phrase;
$score->write_score("$0.mid");
