#!/usr/bin/env perl
use strict;
use warnings;

##
# This is a randomized re-orchestration of Terry Riley's venerable composition, "In C."
##

use lib '.';
use MIDIUtil;
use List::Util qw( shuffle );

# Major (0) or minor (1)?
my $minor = shift // 0;

# Set the number of loop motifs to use
my $max = shift || 8;

# Do or do not shuffle the chosen motifs
my $shuffle = shift // 0;

# Set the number of voices
my $voices = shift || 4;

# General MIDI patches that are audible and aren't horrible
my @patches = qw(
    0 1 2 4 5 7 8 9
    13 16 21 24 25 26
    32 34 35 40 42 60
    68 69 70 71 72 73
    74 79
);

# Initialize the MIDI channel
my $channel = 0;

# Setup the MIDI score
my $score = MIDIUtil::setup_midi( bpm => 120 );

# Declare the available loops
my @loops = (
     \&loop1,  \&loop2,  \&loop3,  \&loop4,  \&loop5,  \&loop6,  \&loop7,  \&loop8,  \&loop9, \&loop10,
    \&loop11, \&loop12, \&loop13, \&loop14, \&loop15, \&loop16, \&loop17, \&loop18, \&loop19, \&loop20,
    \&loop21, \&loop22, \&loop23, \&loop24, \&loop25, \&loop26, \&loop27, \&loop28, \&loop29, \&loop30,
    \&loop31, \&loop32, \&loop33, \&loop34, \&loop35, \&loop36, \&loop37, \&loop38, \&loop39, \&loop40,
    \&loop41, \&loop42, \&loop43, \&loop44, \&loop45, \&loop46, \&loop47, \&loop48, \&loop49, \&loop50,
    \&loop51, \&loop52, \&loop53,
);

# Limit the number of loops to be played to the given max
my @pick;
if ( $shuffle ) {
    @pick = ( shuffle @loops )[ 0 .. $max - 1 ];
}
else {
    @pick = @loops[ 0 .. $max - 1 ];
}

# Generate a phrase for each patch
my @phrases;
for my $voice ( 1 .. $voices ) {
    # Make a procedure to play the chosen loops
    my $proc = sub {
        # Avoid the drum channel
        $channel++ if $channel == 9;

        print "Voice: $voice, Channel: $channel\n";

        # Increment the channel and patch
        MIDIUtil::set_chan_patch( $score, $channel++, random_patch() );

        # Call each of the chosen loops
        $_->() for @pick;
    };

    # Accumulate our phrase functions
    push @phrases, $proc;
}

# Mash the phrases together as MIDI tracks
$score->synch(@phrases);

# Write the score to a MIDI file
$score->write_score("$0.mid");

# Return a number between 1 and 4
sub rand4 {
    return 1 + int rand 4;
}

# Return a random patch!
sub random_patch {
    return $patches[ int rand @patches ];
}

# Available loops:

sub loop1 {
    print "loop1\n";
    for ( 1 .. rand4() ) {
        $score->n( 'qn', $minor ? 'Ds4' : 'E4' ) for 1 .. 3;
    }
}

sub loop2 {
    print "loop2\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'F4' );
        $score->n( 'qn', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop3 {
    print "loop3\n";
    for ( 1 .. rand4() ) {
        $score->r('en');
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'F4' );
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop4 {
    print "loop4\n";
    for ( 1 .. rand4() ) {
        $score->r('en');
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'F4' );
        $score->n( 'en', 'G4' );
    }
}

sub loop5 {
    print "loop5\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'F4' );
        $score->n( 'en', 'G4' );
        $score->r('en');
    }
}

sub loop6 {
    print "loop6\n";
    for ( 1 .. rand4() ) {
        $score->n( 'wn', 'C5' );
        $score->n( 'wn', 'C5' );
    }
}

sub loop7 {
    print "loop7\n";
    for ( 1 .. rand4() ) {
        $score->r('qn') for 1 .. 3;
        $score->r('en');
        $score->n( 'sn', 'C4' ) for 1 .. 2;
        $score->n( 'en', 'C4' );
        $score->r('en');
        $score->r('qn') for 1 .. 3;
    }
}

sub loop8 {
    print "loop8\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dwn', 'G4' );
        $score->n( 'wn', 'F4' );
        $score->n( 'wn', 'F4' );
    }
}

sub loop9 {
    print "loop9\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->r('en');
        $score->r('qn') for 1 .. 3;
    }
}

sub loop10 {
    print "loop10\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop11 {
    print "loop11\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop12 {
    print "loop12\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', 'F4' );
        $score->n( 'en', 'G4' );
        $score->n( 'wn', $minor ? 'As4' : 'B4' );
        $score->n( 'qn', 'C3' );
    }
}

sub loop13 {
    print "loop13\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'den', 'G4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
        $score->n( 'qn', 'G4' );
        $score->r('den');
        $score->n( 'sn', 'G4' );
        $score->n( 'dhn', 'G4' );
    }
}

sub loop14 {
    print "loop14\n";
    for ( 1 .. rand4() ) {
        $score->n( 'wn', 'C5' );
        $score->n( 'wn', $minor ? 'As4' : 'B4' );
        $score->n( 'wn', 'G4' );
        $score->n( 'wn', 'Fs4' );
    }
}

sub loop15 {
    print "loop15\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->r('den');
        $score->r('qn') for 1 .. 3;
    }
}

sub loop16 {
    print "loop16\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'C5' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
    }
}

sub loop17 {
    print "loop17\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'C5' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'C5' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->r('sn');
    }
}

sub loop18 {
    print "loop18\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'den', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop19 {
    print "loop19\n";
    for ( 1 .. rand4() ) {
        $score->r('dqn');
        $score->n( 'dqn', 'G5' );
    }
}

sub loop20 {
    print "loop20\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'den', 'G3' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop21 {
    print "loop21\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dhn', 'Fs4' );
    }
}

sub loop22 {
    print "loop22\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dqn', $minor ? 'Ds4' : 'E4' ) for 1 .. 5;
        $score->n( 'dqn', 'Fs4' );
        $score->n( 'dqn', 'G4' );
        $score->n( 'dqn', $minor ? 'Gs4' : 'A4' );
        $score->n( 'en', $minor ? 'As4' : 'B4' );
    }
}

sub loop23 {
    print "loop23\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'dqn', 'Fs4' ) for 1 .. 5;
        $score->n( 'dqn', 'G4' );
        $score->n( 'dqn', $minor ? 'Gs4' : 'A4' );
        $score->n( 'qn', $minor ? 'As4' : 'B4' );
    }
}

sub loop24 {
    print "loop24\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'Fs4' );
        $score->n( 'dqn', 'G4' ) for 1 .. 5;
        $score->n( 'dqn', $minor ? 'Gs4' : 'A4' );
        $score->n( 'en', $minor ? 'As4' : 'B4' );
    }
}

sub loop25 {
    print "loop25\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'Fs4' );
        $score->n( 'en', 'G4' );
        $score->n( 'dqn', $minor ? 'Gs4' : 'A4' ) for 1 .. 5;
        $score->n( 'dqn', $minor ? 'As4' : 'B4' );
    }
}

sub loop26 {
    print "loop26\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', $minor ? 'Ds4' : 'E4' );
        $score->n( 'en', 'Fs4' );
        $score->n( 'en', 'G4' );
        $score->n( 'en', $minor ? 'Gs4' : 'A4' );
        $score->n( 'dqn', $minor ? 'As4' : 'B4' ) for 1 .. 5;
    }
}

sub loop27 {
    print "loop27\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'en', 'G4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop28 {
    print "loop28\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', 'Fs4' );
        $score->n( 'den', $minor ? 'Ds4' : 'E4' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E4' );
    }
}

sub loop29 {
    print "loop29\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dhn', $minor ? 'Ds4' : 'E4' );
        $score->n( 'dhn', 'G4' );
        $score->n( 'dhn', 'C5' );
    }
}

sub loop30 {
    print "loop30\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dwn', 'C5' );
    }
}

sub loop31 {
    print "loop31\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
    }
}

sub loop32 {
    print "loop32\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'F4' );
        $score->n( 'dhn', 'F4' );
        $score->n( 'dqn', 'G4' );
    }
}

sub loop33 {
    print "loop33\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
        $score->r('en');
    }
}

sub loop34 {
    print "loop34\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
    }
}

sub loop35 {
    print "loop35\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->r('en');
        $score->r('qn') for 1 .. 3;
        $score->n( 'qn', $minor ? 'Gs4' : 'As4' );
        $score->n( 'dhn', 'G5' );
        $score->n( 'en', $minor ? 'Gs4' : 'A5' );
        $score->n( 'en', 'G5' );
        $score->n( 'en', 'G5' );
        $score->n( 'en', $minor ? 'As4' : 'B5' );
        $score->n( 'dqn', $minor ? 'Gs4' : 'A5' );
        $score->n( 'en', 'G5' );
        $score->n( 'dhn', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', 'G5' );
        $score->n( 'en', 'Fs5' );
        $score->n( 'dhn', 'Fs5' );
        $score->r('qn') for 1 .. 2;
        $score->r('en');
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'hn', $minor ? 'Ds4' : 'E5' );
        $score->n( 'dhn', 'F5' );
    }
}

sub loop36 {
    print "loop36\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop37 {
    print "loop37\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop38 {
    print "loop38\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
    }
}

sub loop39 {
    print "loop39\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'C5' );
    }
}

sub loop40 {
    print "loop40\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'F4' );
    }
}

sub loop41 {
    print "loop41\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'As4' : 'B4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop42 {
    print "loop42\n";
    for ( 1 .. rand4() ) {
        $score->n( 'wn', 'C5' );
        $score->n( 'wn', $minor ? 'As4' : 'B4' );
        $score->n( 'wn', $minor ? 'Gs4' : 'A4' );
        $score->n( 'wn', 'C5' );
    }
}

sub loop43 {
    print "loop43\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F5' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E5' );
        $score->n( 'sn', 'F5' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'sn', 'F5' );
        $score->n( 'sn', $minor ? 'Ds4' : 'E5' );
    }
}

sub loop44 {
    print "loop44\n";
    for ( 1 .. rand4() ) {
        $score->n( 'en', 'F5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'en', $minor ? 'Ds4' : 'E5' );
        $score->n( 'qn', 'C5' );
    }
}

sub loop45 {
    print "loop45\n";
    for ( 1 .. rand4() ) {
        $score->n( 'qn', 'D5' );
        $score->n( 'qn', 'D5' );
        $score->n( 'qn', 'G4' );
    }
}

sub loop46 {
    print "loop46\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'D5' );
        $score->n( 'sn', 'C5' );
        $score->n( 'sn', 'D5' );
        $score->r('en');
        $score->n( 'en', 'G4' );
        $score->r('en');
        $score->n( 'en', 'G4' );
        $score->r('en');
        $score->n( 'en', 'G4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', 'D5' );
        $score->n( 'sn', 'C5' );
        $score->n( 'sn', 'D5' );
    }
}

sub loop47 {
    print "loop47\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'D5' );
        $score->n( 'sn', 'C5' );
        $score->n( 'en', 'D5' );
    }
}

sub loop48 {
    print "loop48\n";
    for ( 1 .. rand4() ) {
        $score->n( 'dwn', 'G4' );
        $score->n( 'wn', 'G4' );
        $score->n( 'wn', 'F4' );
        $score->n( 'qn', 'F4' );
    }
}

sub loop49 {
    print "loop49\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'Gs4' : 'As4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'Gs4' : 'As4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop50 {
    print "loop50\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
    }
}

sub loop51 {
    print "loop51\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'F4' );
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'Gs4' : 'As4' );
    }
}

sub loop52 {
    print "loop52\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', 'G4' );
        $score->n( 'sn', $minor ? 'Gs4' : 'As4' );
    }
}

sub loop53 {
    print "loop53\n";
    for ( 1 .. rand4() ) {
        $score->n( 'sn', $minor ? 'Gs4' : 'As4' );
        $score->n( 'sn', 'G4' );
    }
}
