#!/usr/bin/perl
use strict;
use warnings;

use Data::Dumper;local$Data::Dumper::Indent=1;local$Data::Dumper::Terse=1;local$Data::Dumper::Sortkeys=1;

use Math::Combinatorics;
use Music::Chord::Namer qw(chordname);

# Show all names of a permuted chord ("inversions").
my @n = @ARGV ? map { ucfirst } @ARGV : qw(C E G);
my @p = permute(@n);
my %x = ();
my %y = ();
for my $i (@p) {
    for my $c (chordname(@$i)) {
        push @{$x{$c}}, "@$i";
        push @{$y{"@$i"}}, $c;
    }
}
warn Dumper(\%x, \%y);

__END__
perl chordname c\# e gb
