#!/usr/bin/env perl

# 

use strict;
use warnings;

use lib '/Users/gene/sandbox/MIDI-Util/lib';
use MIDI::Util;
use Music::Scales;
use Music::Voss qw/ powers /;

my $max = shift || 64;
my $bpm = shift || 20;

my $scale_note          = 'A';
my $alto_scale_name     = 'minor';
my $tenor_scale_name    = 'pminor';
my $baritone_scale_name = 'pminor';

my $alto_patch     = 69;
my $tenor_patch    = 70;
my $baritone_patch = 42;

my $quarter = 'qn';
my $half    = 'hn';
my $whole   = 'wn';

my $score = MIDI::Util::setup_score( lead_in => 0, bpm => $bpm );

$score->synch(
    \&alto,
    \&tenor,
    \&baritone,
);

$score->write_score("$0.mid");

sub alto {
    MIDI::Util::set_chan_patch( $score, 0, $alto_patch );

    my @alto_scale = map { $_ . 5 } get_scale_notes( $scale_note, $alto_scale_name );
    my $alto_seed  = [ map { sub { int rand 2 } } @alto_scale ];
    my $alto_genf  = powers( calls => $alto_seed );

    my $i = 0;

    for my $n ( 0 .. $max - 1 ) {
        if ( $n % 4 == 0 ) {
            for ( 1 .. 4 ) {
                my $note = $alto_scale[ $alto_genf->($n) ];
                $score->n( $quarter, $note );
            }

            if ( $i % 3 == 0 ) {
                my $note = $alto_scale[ $alto_genf->($n) ];
                $score->n( $quarter, $note );
            }
        }
        else {
            $score->r($whole);
        }

        $i++;
    }

    $score->r($whole);
}

sub tenor {
    MIDI::Util::set_chan_patch( $score, 1, $tenor_patch );

    my @tenor_scale = map { $_ . 4 } get_scale_notes( $scale_note, $tenor_scale_name );
    my $tenor_seed  = [ map { sub { int rand 2 } } @tenor_scale ];
    my $tenor_genf  = powers( calls => $tenor_seed );

    for my $n ( 0 .. $max - 1 ) {
        if ( $n < 8 ) {
            $score->r($whole);
        }
        else {
            if ( $n % 2 == 0 ) {
                my $note = $tenor_scale[ $tenor_genf->($n) ];
                $score->n( $half, $note );
            }
            else {
                $score->r($half);
            }

            if ( $n % 3 == 0 ) {
                my $note = $tenor_scale[ $tenor_genf->($n) ];
                $score->n( $half, $note );
            }
            else {
                $score->r($half);
            }
        }
    }

    $score->n( $whole, $tenor_scale[0] );
}

sub baritone {
    MIDI::Util::set_chan_patch( $score, 2, $baritone_patch );

    my @baritone_scale = map { $_ . 3 } get_scale_notes( $scale_note, $baritone_scale_name );
    my $baritone_seed  = [ map { sub { int rand 2 } } @baritone_scale ];
    my $baritone_genf  = powers( calls => $baritone_seed );

    for my $n ( 0 .. $max - 1 ) {
        if ( $n < 8 ) {
            $score->r($whole);
        }
        else {
            my $note = $baritone_scale[ $baritone_genf->($n) ];
            $score->n( $whole, $note );
        }
    }

    $score->n( $whole, $baritone_scale[0] );
}
