#!/usr/bin/env perl
use strict;
use warnings;

use lib $ENV{HOME} . '/sandbox/MIDI-Util/lib';
use MIDI::Util;
use Data::Dumper::Compact 'ddc';

$Data::Dumper::Varname = 'Length';
print ddc(MIDI::Util::dump('length'));

__END__
volume
length
note
note2number
number2note
patch2number
number2patch
notenum2percussion
percussion2notenum
all_events
midi_events
meta_events
text_events
nontext_meta_events
