#!/usr/bin/env perl

# Charlie Parker, Mohawk (B♭ major/G minor)
# https://jazz.okstate.edu/wp-content/uploads/2019/06/Mohawk-lead-sheet-piano-guitar-PianoGuitar.pdf

use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(Music-Bassline-Generator MIDI-Chord-Guitar Music-Duration MIDI-Drummer-Tiny MIDI-Praxis-Variation MIDI-Util); # local author libs
use Music::Bassline::Generator;
use MIDI::Drummer::Tiny;
use MIDI::Chord::Guitar;
use MIDI::Praxis::Variation qw(tie_durations);
use MIDI::Util qw(set_chan_patch);

my $repeat = shift || 2;
my $bpm    = shift || 162;

my $chord_patch  = 4;  # Electric Piano 1
my $bass_patch   = 35; # Fretless Bass
my $melody_patch = 66; # Tenor Sax
my $channel      = 0;  # Internal increment

my $d = MIDI::Drummer::Tiny->new(
    file => $0 . '.mid',
    bpm  => $bpm,
    bars => 24,
);

$d->sync(
    \&drums,
    \&chords,
    \&melody,
    \&bass,
);

$d->write;

sub drums {
    $d->count_in(1);
    for my $n (1 .. $d->bars * $repeat) {
        $d->note($d->quarter,        $d->ride1, $d->kick);
        $d->note($d->triplet_eighth, $d->ride1);
        $d->rest($d->triplet_eighth);
        $d->note($d->triplet_eighth, $d->ride1);
    }
}

sub chords {
    set_chan_patch($d->score, $channel++, $chord_patch);

    # (Local voicing file used on the author's machine.)
    my $mcg = MIDI::Chord::Guitar->new(voicing_file => "$ENV{HOME}/sandbox/MIDI-Chord-Guitar/share/midi-guitar-chord-voicings.csv");

    my $Bf7   = $mcg->transform('Bb2', '7',   3);
    my $Ef7   = $mcg->transform('Eb3', '7',   1);
    my $Fm7   = $mcg->transform('F3',  'm7',  1);
    my $Bf7f9 = $mcg->transform('Bb2', '7b9', 0);
    my $Efm7  = $mcg->transform('Eb3', 'm7',  1);
    my $Dm7   = $mcg->transform('D3',  'm7',  1);
    my $G7f9  = $mcg->transform('G2',  '7b9', 0); # b13
    my $Cm7   = $mcg->transform('C3',  'm7',  1);
    my $F7    = $mcg->transform('F2',  '7',   3);

    $d->rest($d->whole); # while counting-in

    for my $n (1 .. $repeat) {
        $d->note($d->whole, @$Bf7);
        $d->note($d->whole, @$Ef7);
        $d->note($d->whole, @$Bf7);
        $d->note($d->half,  @$Fm7);
        $d->note($d->half,  @$Bf7f9);
        $d->note($d->whole, @$Ef7);
        $d->note($d->whole, @$Efm7);
        $d->note($d->whole, @$Dm7);
        $d->note($d->whole, @$G7f9);
        $d->note($d->whole, @$Cm7);
        $d->note($d->whole, @$F7);
        $d->note($d->whole, @$Bf7);
        $d->note($d->half,  @$Cm7);
        $d->note($d->half,  @$F7);
    }
}

sub bass {
    set_chan_patch($d->score, $channel++, $bass_patch);

    my $bassline = Music::Bassline::Generator->new(
        verbose   => 0,
        octave    => 2,
        guitar    => 1,
        wrap      => 'C3',
        modal     => 1,
        keycenter => 'Bb',
    );

    $d->rest($d->whole); # while counting-in

    for my $n (1 .. $repeat) {
        _walk($bassline, 'Bb7',   2);
        _walk($bassline, 'Eb7',   2);
        _walk($bassline, 'Bb7',   2);
        _walk($bassline, 'Fm7',   1);
        _walk($bassline, 'Bb7b9', 1);
        _walk($bassline, 'Eb7',   2);
        _walk($bassline, 'Ebm7',  2);
        _walk($bassline, 'Dm7',   2);
        _walk($bassline, 'G7b9',  2);
        _walk($bassline, 'Cm7',   2);
        _walk($bassline, 'F7',    2);
        _walk($bassline, 'Bb7',   1);
        _walk($bassline, 'Cm7',   1);
        _walk($bassline, 'F7',    2);
    }
}

sub _walk {
    my ($bassline, $chord, $n) = @_;
    my $notes = $bassline->generate($chord, $n);
    $d->note('hn', $_) for @$notes;
}

sub melody {
    set_chan_patch($d->score, $channel++, $melody_patch);

    $d->rest('d' . tie_durations($d->dotted_half, $d->eighth)); # while counting-in

    for my $n (1 .. $repeat) {
        $d->note($d->dotted_quarter, 'Bf4'); # tie->

        $d->note($d->eighth, 'A4');
        $d->note($d->eighth, 'Fs4');
        $d->note($d->eighth, 'G4');
        $d->note($d->eighth, 'Bf4');
        $d->note($d->eighth, 'C5');
        $d->note($d->eighth, 'D5');

        $d->note($d->quarter, 'Ef5');
        $d->rest($d->eighth);
        $d->note($d->quarter, 'Gf4');
        $d->note($d->quarter, 'Df5');
        $d->note($d->eighth, 'Bf4');

        $d->note($d->triplet_eighth, 'C5');
        $d->note($d->triplet_eighth, 'Df5');
        $d->note($d->triplet_eighth, 'C5');
        $d->note($d->eighth, 'Bf4');
        $d->note($d->eighth, 'G4');
        $d->note($d->quarter, 'Bf4');
        $d->note($d->triplet_eighth, 'F4');
        $d->note($d->triplet_eighth, 'Af4');
        $d->note($d->triplet_eighth, 'Ef5');

        $d->note($d->eighth, 'G5');
        $d->note($d->eighth, 'F5');
        $d->note($d->quarter, 'G5');
        $d->rest($d->eighth);
        $d->note($d->quarter, 'F5');
        $d->note($d->eighth, 'Ef5');

        $d->note($d->quarter, 'F5');
        $d->rest($d->eighth);
        $d->note($d->quarter, 'Bf4');
        $d->note($d->quarter, 'C5');
        $d->note($d->quarter, 'Bf4'); # tie->

        $d->note($d->quarter, 'F5');
        $d->note($d->eighth, 'Ef5');
        $d->note($d->eighth, 'Bf4');
        $d->note($d->eighth, 'Gf4');
        $d->note($d->eighth, 'D5');
        $d->note($d->dotted_quarter, 'A4'); # tie->

        $d->rest($d->eighth);
        $d->note($d->eighth, 'F5');
        $d->note($d->quarter, 'C5');
        $d->rest($d->eighth);
        $d->note($d->eighth, 'F5');

        $d->note($d->triplet_eighth, 'D5');
        $d->note($d->triplet_eighth, 'Ef5');
        $d->note($d->triplet_eighth, 'F5');
        $d->note($d->triplet_eighth, 'D5');
        $d->note($d->triplet_eighth, 'Bf4');
        $d->note($d->triplet_eighth, 'Ef5');
        $d->rest($d->dotted_quarter);
        $d->note($d->quarter, 'D5'); # tie->

        $d->note($d->quarter, 'Bf4');
        $d->note($d->eighth, 'G4');
        $d->note($d->eighth, 'Bf4');
        $d->note($d->eighth, 'G4');
        $d->note($d->quarter, 'Bf4');

        $d->rest($d->eighth);
        $d->note($d->quarter, 'Bf4');
        $d->note($d->eighth, 'G4');
        $d->rest($d->eighth);
        $d->note($d->quarter, 'Bf4');
        $d->note($d->dotted_quarter, 'D5'); # tie->

        $d->note($d->eighth, 'Bf4');
        $d->note($d->eighth, 'F4');
        $d->note($d->eighth, 'Af4');
        $d->note($d->eighth, 'F4');
        $d->note($d->eighth, 'G4');
        $d->note($d->dotted_quarter, 'F4'); # tie->

        $d->rest($d->eighth);
        $d->note($d->eighth, 'F4');
        $d->note($d->eighth, 'Af4');
        $d->note($d->eighth, 'F4');
        $d->note($d->eighth, 'A4');
    }

    $d->note($d->dotted_quarter, 'Bf4');
}
