#!/usr/bin/env perl
use strict;
use warnings;

use MIDI;
use Statistics::Frequency;

my $file = shift || die "Usage: perl $0 file.mid\n";

my $opus = MIDI::Opus->new({ from_file => $file });

my $transitions = {};

for my $t ( $opus->tracks ) {
    my @events = grep { $_->[0] eq 'note_on' } $t->events;
    next unless @events;

    my $last;

    for my $event ( @events ) {
        next unless $event->[2] == 0; # Skip all but channel 0

        if ( $last ) {
            my $next = $event->[3]; # The next note in succession
            push @{ $transitions->{$last} }, $next;
warn "Datum: $last -> $next\n";
            $last = $next;
        }
        else {
            $last = $event->[3]; # The note value
        }
    }
}
use Data::Dumper;warn 'Note transitions: ', Dumper$transitions;

my $frequencies = {};

my $stat = Statistics::Frequency->new;

for my $note ( keys %$transitions ) {
    $stat->add_data( @{ $transitions->{$note} } );
    $frequencies->{$note} = { $stat->proportional_frequencies };
    $stat->clear_data;
}
use Data::Dumper;warn 'Transition frequencies: ', Dumper$frequencies;
