debug: 1
device: Synido TempoPAD Z-1
triggers:
  - event: 'note-on'
    data: 'C1'
    text: '^'
  - event: 'note-on'
    data: 'C#1'
    text: 'g_'
  - event: 'note-on'
    data: 'D1'
    text: ':set spell!'
  - event: 'note-on'
    data: 'D#1'
    text: ':set list!'
  - event: 'note-on'
    data: 'E1'
    text: 'zb'
  - event: 'note-on'
    data: 'F1'
    text: 'zt'
  - event: 'note-on'
    data: 'F#1'
    text: 'zc'
  - event: 'note-on'
    data: 'G1'
    text: 'zv'
  - event: 'note-on'
    data: 'G#1'
    key: 'ctrl+g'
  - event: 'note-on'
    data: 'A1'
    key: 'ctrl+p'
  - event: 'note-on'
    data: 'A#1'
    key: 'ctrl+n'
  - event: 'note-on'
    data: 'B1'
    text: ':!git blame %'
  - event: 'note-on'
    data: 'C2'
    text: 'gT'
  - event: 'note-on'
    data: 'C#2'
    text: 'gt'
  - event: 'note-on'
    data: 'D2'
    text: ':tabnew'
  - event: 'note-on'
    data: 'D#2'
    text: ':Explore .'
  - event: 'note-on'
    data: 'E2'
    key: 'ctrl+y'
  - event: 'note-on'
    data: 'F2'
    key: 'ctrl+e'
  - event: 'note-on'
    data: 'F#2'
    text: '{'
  - event: 'note-on'
    data: 'G2'
    text: '}'
  - event: 'note-on'
    data: 'G#2'
    text: 'b'
  - event: 'note-on'
    data: 'A2'
    text: 'w'
  - event: 'note-on'
    data: 'A#2'
    text: 'F '
  - event: 'note-on'
    data: 'B2'
    text: 'f '
  - event: 'note-on'
    data: 'C3'
    text: ':tab ball'
  - event: 'note-on'
    data: 'C#3'
    text: ':S'
  - event: 'note-on'
    data: 'D3'
    text: ':echo expand("%:p")'
  - event: 'note-on'
    data: 'D#3'
    text: ':call DoTidy()'
  - event: 'note-on'
    data: 'E3'
    text: ' ;ul'
  - event: 'note-on'
    data: 'F3'
    text: ' ;iv'
  - event: 'note-on'
    data: 'F#3'
    text: ' ;my'
  - event: 'note-on'
    data: 'G3'
    text: ' ;dt'
  - event: 'note-on'
    data: 'G#3'
    text: ':set ft=perl'
  - event: 'note-on'
    data: 'A3'
    text: ':set ft=html'
  - event: 'note-on'
    data: 'A#3'
    text: ':set ft=javascript'
  - event: 'note-on'
    data: 'B3'
    text: ':w !jshint %'
  - event: 'note-on'
    data: 'C4'
    text: ' ;ww'
  - event: 'note-on'
    data: 'C#4'
    text: ' ;dd'
  - event: 'note-on'
    data: 'D4'
    text: ' ;ll'
  - event: 'note-on'
    data: 'D#4'
    text: ':r !date'
  - event: 'note-on'
    data: 'E4'
    text: ':w'
  - event: 'note-on'
    data: 'F4'
    text: ':qa'
  - event: 'note-on'
    data: 'F#4'
    text: ':qa!'
  - event: 'note-on'
    data: 'G4'
    text: ':digraphs'
  - event: 'note-on'
    data: 'G#4'
    text: ' cd'
  - event: 'note-on'
    data: 'A4'
    text: ' cl'
  - event: 'note-on'
    data: 'A#4'
    text: ' cc'
  - event: 'note-on'
    data: 'B4'
    text: ' cp'
  - event: 'note-on'
    data: 'C5'
    text: ' ps'
  - event: 'note-on'
    data: 'C#5'
    text: ' pr'
  - event: 'note-on'
    data: 'D5'
    text: ' pc'
  - event: 'note-on'
    data: 'D#5'
    text: ' ;s'
  - event: 'note-on'
    data: 'E5'
    key: 'ctrl+h'
  - event: 'note-on'
    data: 'F5'
    key: 'ctrl+l'
  - event: 'note-on'
    data: 'F#5'
    key: 'ctrl+j'
  - event: 'note-on'
    data: 'G5'
    key: 'ctrl+k'
  - event: 'note-on'
    data: 'G#5'
    key: 'ctrl+m'
  - event: 'note-on'
    data: 'A5'
    key: 'ctrl+n'
  - event: 'note-on'
    data: 'A#5'
    key: 'ctrl+x'
  - event: 'note-on'
    data: 'B5'
    key: 'ctrl+a'
  - event: 'note-on'
    data: 'C6'
    key: 'ctrl+w'
  - event: 'note-on'
    data: 'C#6'
    text: '~'
  - event: 'note-on'
    data: 'D6'
    text: 'u'
  - event: 'note-on'
    data: 'D#6'
    key: 'ctrl+r'
