#!/usr/bin/env perl
use strict;
use warnings;

use Graph::Weighted;
#use List::Util::WeightedChoice qw( choose_weighted );
#use MIDI::Simple;
use Storable;

my $file    = shift || die "Usage: perl $0 proportional-frequencies.dat [0|1]";
my $initial = shift // 1; # Initial graph node: 0=random, 1=lowest note

my $data = retrieve($file);
#use Data::Dumper::Concise;warn Dumper$data;

if ( $initial == 0 ) {
    $initial = ( keys %$data )[ int( rand keys %$data ) ];
}
else {
    $initial = ( sort { $a <=> $b } keys %$data )[0];
}
#warn __LINE__,". MARK: ",$initial,"\n";

#my $notes = Graph::Weighted->new();
#$notes->populate($data);
#use Data::Dumper::Concise;warn Dumper$notes;
