#!/usr/bin/env perl
use strict;
use warnings;

use Algorithm::Combinatorics qw( variations );
use MIDIUtil;
 
my $data = shift || '0 C5 Ds5 A5';
my $bass = shift || 'C4 F4 G4';
my $bpm  = shift || 400;

my @data = split / /, $data;
my @bass = split / /, $bass;

my $size = 0;

my $score = MIDIUtil::setup_midi( bpm => $bpm );

$score->synch(
    \&variance,
    \&legato,
);

$score->write_score( "$0.mid" );

sub variance {
    MIDIUtil::set_chan_patch( $score, 0, 69 );

    my $c = 1;

    for my $n ( 1 .. @data ) {
        my @items = variations( \@data, $n );

        for my $i (@items) {
            print "$c. @$i\n";
            $c++;

            for my $x ( @$i ) {
                if ( $x eq '0' ) {
                    $score->r('qn');
                }
                else {
                    $score->n( 'qn', $x );
                }

                $size++;
            }
        }
    }
}

sub legato {
    MIDIUtil::set_chan_patch( $score, 1, 42 );
    $score->Volume(60);

    my @notes = grep { $_ ne '0' } @bass;

    for my $n ( 1 .. length($size) / 4 ) {
        $score->n( 'wn', $notes[ int rand @notes ] );
    }
}
