#!/usr/bin/env perl

# "Musimathics" pg. 358 - Voss's Method

use strict;
use warnings;

=for curiosity
 for my $n ( 0 .. 15 ) {
    for my $k ( 0 .. 3 ) {
        my $x = 2 ** $k;
        my $y = $n % $x;
        print "$n % 2 ** $k ($x) = $y\n";
        print "\t*\n" if $y == 0;
    }
 }
 exit;
=cut

my $max   = shift || 16;
my @notes = @ARGV ? @ARGV : qw( C5 Ds5 F5 G5 A5 );

my @seed = map { rand_range( 0, 1 ) } 1 .. 4;

my @result;

for my $n ( 0 .. $max - 1 ) {
    my $x = voss( $n, \@seed );
    my $y = sprintf '%.0f', $x; # XXX This is questionable

    $result[$n] = $notes[$y];

    warn "$x => $y => $result[$n]\n";
}

sub voss {
    my ( $n, $list ) = @_;

    my $sum = 0;

    for my $k ( 0 .. @$list - 1 ) {
        if ( $n % ( 2 ** $k ) == 0 ) {
            $list->[$k] = rand_range( -1, 1 );
        }

        $sum += $list->[$k];
    }

    return $sum;
}

sub rand_range {
    my ( $lower, $upper ) = @_;
    my $n = rand() * ( $upper - $lower ) + $lower;
    return $n;
}
