#!/usr/bin/env perl

# "Musimathics" pg. 358 - Voss's Method

use strict;
use warnings;

use Math::Random::OO::Uniform;

=for curiosity
 for my $n ( 0 .. 15 ) {
    for my $k ( 0 .. 3 ) {
        my $x = 2 ** $k;
        my $y = $n % $x;
        print "$n % 2 ** $k ($x) = $y\n";
        print "\t*\n" if $y == 0;
    }
 }
 exit;
=cut

my $max   = shift || 16;
my @notes = @ARGV ? @ARGV : qw( C5 Ds5 F5 G5 A5 );

my $zero_to_one    = Math::Random::OO::Uniform->new;
my $neg_one_to_one = Math::Random::OO::Uniform->new( -1, 1 );

my @seed = map { $zero_to_one->next } 1 .. 4;

my @result;

for my $n ( 0 .. $max - 1 ) {
    my $x = voss( $n, \@seed );
    my $y = sprintf '%.0f', $x; # XXX This is questionable

    $result[$n] = $notes[$y];

    warn "$x => $y => $result[$n]\n";
}

sub voss {
    my ( $n, $list ) = @_;

    my $sum = 0;

    for my $k ( 0 .. @$list - 1 ) {
        if ( $n % ( 2 ** $k ) == 0 ) {
            $list->[$k] = $neg_one_to_one->next;
        }

        $sum += $list->[$k];
    }

    return $sum;
}
